"""
Django settings for styleleveling project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'corsheaders',
    'catalog',
    'rest_framework',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'styleleveling.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'styleleveling.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

PROXY_LIST = [
    'http://45.137.43.0:1081',
    'http://147.45.60.139:1082',
    'http://69.55.49.177:38182',
    'http://66.42.224.229:41679',
    'http://129.153.194.16:1080',
    'http://192.252.215.5:16137',
    'http://70.166.167.38:57728',
    'http://98.178.72.21:10919',
    'http://174.77.111.198:49547',
    'http://72.195.34.60:27391',
    'http://184.170.251.30:11288',
    'http://192.111.129.145:16894',
    'http://192.111.137.37:18762',
    'http://192.111.130.5:17002',
    'http://192.111.137.34:18765',
    'http://192.252.220.92:17328',
    'http://198.8.94.174:39078',
    'http://115.127.53.114:1080',
    'http://46.0.229.208:1080',
    'http://79.111.14.142:1080',
    'http://202.62.62.113:1080',
    'http://124.248.177.44:1080',
    'http://45.43.63.37:10808',
    'http://47.245.165.201:1080',
    'http://144.91.111.48:1088',
    'http://95.211.190.26:9100',
    'http://69.61.200.104:36181',
    'http://47.82.123.15:1011',
    'http://101.36.104.239:10808',
    'http://212.58.132.5:1080',
    'http://171.25.158.95:1080',
    'http://195.19.50.79:1080',
    'http://144.91.121.61:1088',
    'http://195.19.49.4:1080',
    'http://159.195.67.82:32769',
    'http://43.164.136.189:1080',
    'http://70.166.167.55:57745',
    'http://46.146.210.123:1080',
    'http://101.36.104.46:10808',
    'http://43.164.3.124:1080',
    'http://184.178.172.13:15311',
    'http://46.146.216.44:1080',
    'http://185.185.80.58:1088',
    'http://104.234.124.3:1080',
    'http://98.170.57.249:4145',
    'http://98.191.0.47:4145',
    'http://98.170.57.241:4145',
    'http://98.170.57.231:4145',
    'http://98.175.31.195:4145',
    'http://98.181.137.83:4145',
    'http://98.181.137.80:4145',
    'http://98.175.31.222:4145',
    'http://184.178.172.28:15294',
    'http://68.1.210.189:4145',
    'http://92.118.234.124:1080',
    'http://184.181.178.33:4145',
    'http://47.238.236.151:5555',
    'http://72.195.34.59:4145',
    'http://193.233.218.213:1080',
    'http://184.182.240.12:4145',
    'http://184.178.172.25:15291',
    'http://192.111.139.163:19404',
    'http://184.181.217.201:4145',
    'http://192.252.210.233:4145',
    'http://199.66.183.226:4145',
    'http://144.24.111.128:1088',
    'http://24.249.199.4:4145',
    'http://184.178.172.3:4145',
    'http://184.181.217.194:4145',
    'http://142.54.237.38:4145',
    'http://67.201.35.145:4145',
    'http://192.252.211.193:4145',
    'http://67.201.39.14:4145',
    'http://68.71.242.118:4145',
    'http://67.201.58.190:4145',
    'http://72.205.0.93:4145',
    'http://192.252.214.17:4145',
    'http://199.66.183.251:4145',
    'http://199.66.182.243:4145',
    'http://147.45.60.136:1082',
    'http://45.194.33.12:30001',
    'http://138.2.216.186:1080',
    'http://144.24.47.42:1080',
    'http://70.166.65.160:4145',
    'http://184.178.172.5:15303',
    'http://98.175.31.195:4145',
    'http://130.49.187.61:1082',
    'http://147.45.60.124:1082',
    'http://178.130.47.21:1082',
    'http://149.62.186.244:1080',
    'http://103.75.118.84:1080',
    'http://72.223.188.92:4145',
    'http://107.152.98.5:4145',
    'http://104.200.135.46:4145',
    'http://184.178.172.17:4145',
    'http://68.1.210.163:4145',
    'http://72.37.217.3:4145',
    'http://142.54.226.214:4145',
    'http://107.181.161.81:4145',
    'http://45.179.145.12:6080',
    'http://144.124.227.88:3129',
    'http://121.169.46.116:1090',
    'http://142.54.232.6:4145',
    'http://192.252.220.89:4145',
    'http://68.71.245.206:4145',
    'http://192.252.216.86:4145',
    'http://72.207.113.97:4145',
    'http://68.71.251.134:4145',
    'http://216.68.128.121:4145',
    'http://72.49.49.11:31034',
    'http://193.25.215.182:22222',
    'http://192.111.138.29:4145',
    'http://72.37.216.68:4145',
    'http://192.111.129.150:4145',
    'http://72.207.33.64:4145',
    'http://220.158.232.118:1080',
    'http://123.58.219.171:10808',
    'http://212.48.150.38:1080',
    'http://72.214.108.67:4145',
    'http://43.160.255.142:7890',
    'http://192.252.216.81:4145',
    'http://72.195.34.41:4145',
    'http://198.8.84.3:4145',
    'http://199.102.107.145:4145',
    'http://72.195.101.99:4145',
    'http://51.15.253.45:8080',
    'http://199.229.254.129:4145',
    'http://184.185.2.12:4145',
    'http://184.178.172.5:15303',
    'http://184.178.172.23:4145',
    'http://206.220.175.2:4145',
    'http://184.170.245.148:4145',
    'http://199.58.184.97:4145',
    'http://199.102.104.70:4145',
    'http://184.181.217.210:4145',
    'http://184.181.217.220:4145',
    'http://184.170.249.65:4145',
    'http://72.195.114.184:4145',
    'http://24.249.199.12:4145',
    'http://194.163.174.78:1087',
    'http://184.181.217.213:4145',
    'http://184.178.172.26:4145',
    'http://184.181.217.206:4145',
    'http://174.75.211.222:4145',
    'http://198.8.94.170:4145',
    'http://192.111.130.2:4145',
    'http://192.252.208.67:14287',
    'http://192.252.214.20:15864',
    'http://192.252.208.70:14282',
    'http://142.54.236.97:4145',
    'http://199.116.114.11:4145',
    'http://174.77.111.196:4145',
    'http://174.77.111.197:4145',
    'http://72.195.34.58:4145',
    'http://162.253.68.97:4145',
    'http://147.45.60.246:1082',
    'http://184.182.240.211:4145',
    'http://184.178.172.14:4145',
    'http://142.54.239.1:4145',
    'http://67.201.33.10:25283',
    'http://185.185.80.58:1088',
    'http://77.110.102.252:1080',
    'http://89.208.106.37:32712',
    'http://172.81.111.156:10001',
    'http://72.195.34.35:27360',
    'http://3.128.83.74:17000',
    'http://152.32.203.130:10808',
    'http://109.172.7.42:1080',
    'http://208.102.51.6:58208',
    'http://109.199.105.194:1080',
    'http://184.178.172.18:15280',
    'http://178.17.57.222:1080',
    'http://47.236.177.236:1080',
    'http://159.195.49.27:1080',
    'http://192.111.135.18:18301',
    'http://192.252.211.197:14921',
    'http://67.201.33.10:25283',
]

# Optional: Add authentication if any of your proxies need it
# If you have proxies with authentication, use this format:
# 'http://username:password@45.137.43.0:1081'
